version: '3'

services:
  api:
    build: ./api
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api:/src
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    depends_on:
      - db

  # web:
  #   build: ./web
  #   volumes:
  #     - ./web:/app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - api
  #   environment:
  #     - API_URL=http://api:8000

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
